on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_call:

name: Tests

jobs:
  tests:
    runs-on: "ubuntu-latest"
    
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: run tests
        run: cargo test
